[project]
name = "spade-rpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aioxmpp",
    "click>=8.4.1",
    "loguru>=0.7.3",
    "pytz==2022.1", # FIXME: update to >=2026.2 when spade updates
    "spade>=4.1.4",
]

[tool.uv.sources]
aioxmpp = { path = "../aioxmpp", editable = true }
